[package]
name = "surrealism-ui"
version = "0.4.0"
edition = "2024"
description = "SurrealismUI is a third-party component library built entirely using Slint"
authors = ["syf20020816@outlook.com"]
license = "MIT"
repository = "https://github.com/syf20020816/SurrealismUI"
documentation = "https://github.com/syf20020816/SurrealismUI"
keywords = ["slint-ui", "slint","ui-components"]


[dependencies]
slint = "1.4.1"
